name: Release Charts

on:
  workflow_dispatch:
    inputs:
        version_tag:
          description: 'The target version tag for the release (e.g., 1.2.3)'
          required: true
          type: string

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate chart version
        run: |
          CHART_VERSION=$(grep '^version:' charts/hello-world/Chart.yaml | awk '{print $2}')
          INPUT_VERSION="${{ inputs.version_tag }}"
          INPUT_VERSION="${INPUT_VERSION#v}"

          echo "Chart version: $CHART_VERSION"
          echo "Release version: $INPUT_VERSION"

          if [ "$CHART_VERSION" != "$INPUT_VERSION" ]; then
            echo "Version mismatch!"
            exit 1
          fi

          echo "Versions match!"
          
      - name: Check release version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh release view "${{ inputs.version_tag }}" > /dev/null 2>&1; then
            echo "Release ${{ inputs.version_tag }} already exists!"
            exit 1
          fi

  release:
    needs: version-check
    permissions:
        contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
            
      - name: Setup Helm
        uses: azure/setup-helm@v5
        with:
          version: v3.22.0
 
      - name: Package Helm chart
        run: |
          cd charts/hello-world
          helm package .
          echo "Helm chart packaged successfully"
      
      - name: Create GitHub Release
        run: |
          gh release create "${{ inputs.version_tag }}" \
            charts/hello-world/*.tgz \
            --generate-notes \
            --title "${{ inputs.version_tag }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}